// <auto-generated />
namespace EventFeedback.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class FeedbackDefinition2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeedbackDefinition2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311071102179_FeedbackDefinition2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
