// <auto-generated />
namespace EventFeedback.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Domain_MoreFeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Domain_MoreFeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "201310110749583_Domain_MoreFeedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
