// <auto-generated />
namespace EventFeedback.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Domain_ResourceText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Domain_ResourceText));
        
        string IMigrationMetadata.Id
        {
            get { return "201310101007347_Domain_ResourceText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
