// <auto-generated />
namespace EventFeedback.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class FeedbackDefinition3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeedbackDefinition3));
        
        string IMigrationMetadata.Id
        {
            get { return "201311071137468_FeedbackDefinition3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
